@startuml
actor Client #black
participant Batch as "BatchProcess"
participant N as "Next.ts"
participant API as "Spring"
participant S3
participant CloudFront

Batch->N: ビルド要求
N->API: ビルド時にjson取得要求(APIKeyによってアクセス制御, 認証機能なし, ユーザごとではなく、一括で更新をかける)
API->RDS: json取得
RDS->API: jsonを返却
API->N: jsonを返却
N->S3: ビルドして生成したファイルをアップロード
Client->CloudFront: https://{ユーザが取得したドメイン} or https://{workspace_name}.{アプリのURL}
CloudFront->S3: キャッシュが無ければ取得
S3->CloudFront: ファイル渡す
CloudFront->Client: .html/.js/.css/画像ファイルを返却

legend center
  Given: JSONは作成済み(RDSに保存)
  When: ビルドの定期ジョブ実行時
  When: ユーザが閲覧目的でアクセスした時
endlegend
@enduml